#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html;
sudo chmod 777 /etc/nginx/sites-available/
sudo chmod 777 /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i "/listen 80 default_server;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/ a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sed -i "/listen 80 default_server;/ a error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx start
