#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.

infinit=0
while((infinit==0));
do
    echo "To infinity and beyond"
    trap "echo I am invincible!!!" SIGTERM
    sleep 2
done
